/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 16.0.0 -fPIC -O3) */

module top(a, b, clk, y);
  input a;
  wire a;
  input b;
  wire b;
  input clk;
  wire clk;
  output y;
  reg y;
  wire _0_;
  AND2_X1 _1_ (
    .A1(a),
    .A2(b),
    .ZN(_0_)
  );
  always @(posedge clk)
    y <= _0_;
endmodule
